name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: mhils/workflows/checkout@acc73c7af100db9fb3f1ad3c0178d382048e943f
      - uses: mhils/workflows/setup-uv@acc73c7af100db9fb3f1ad3c0178d382048e943f

      - run: uv lock

      - uses: mhils/workflows/uv-sync@acc73c7af100db9fb3f1ad3c0178d382048e943f

      - run: ruff check --fix-only .
      - run: ruff format .

      - run: web/gen/all

      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .github/node-version.txt
      - run: npm ci
        working-directory: web
      - run: npm run eslint
        working-directory: web
        continue-on-error: true
      - run: npm run prettier
        working-directory: web

      - uses: mhils/add-pr-ref-in-changelog@main

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
